spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account
    username: postgres
    password: postgres
  jpa:
    show-sql: true

build:
  version: "1.0.0-DEV"

account:
  message: "Welcome to microservice account (PROD env from GitHub)"
  contactDetails:
    name: "Alfrendo Silalahi ~ Tech Lead"
    email: alfrendosilalahi@email.com
  onCallSupport:
    - 12345
    - 67890
